title: Om-Conf
author: Rabimba Karanjai
email: rabimba@rabimba.me
description: > # this means to ignore newlines until "baseurl:"
  
show_excerpts: true # set to false to remove excerpts on the homepage

